blog/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls import url

urlpatterns = [
    url('admin/', admin.site.urls),
    path('blog/', include('blog_app.urls', namespace='blog')),
]

blog_app/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),#we use <> so the <parameter> will be defined as readable url with integers 
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    ] 

blog_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse #gives opportunity to get url after entering its name of draft and parameters
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
            self.publish.month, self.publish.day, self.slug])
    
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() #default manager
    published = PublishedManager() #my new manager
    tags = TaggableManager() #this manager allows to add, get list of tags and del them from the posts

    class Meta:
        ordering = ('-publish',)

        def __str__(self):
            return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)
    

blog_app/forms.py
from .models import Comment
from django import forms
from django.forms import ModelForm

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import CommentForm
from taggit.models import Tag
from django.db.models import Count #agregates, counts the amount of tags in db level

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None #this will be in URL 

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug) #making  a queryst and getting the tagged objects with get404
        object_list = object_list.filter(tags__in=[tag]) #filter all the posts getting only the posts that are related to the tag (many to many)
    
    paginator = Paginator(object_list, 4) #4 posts on each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger: #if page not int return the 1st page
        posts = paginator.page(1)
    except EmptyPage: #if the number of the page is more than exist then return the very last page
        posts = paginator.page(pagination.num_pages)
    return render(request, 'blog/post/list.html', 
    {'page': page, 'posts': posts, 'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, slug=post, status='published', 
        publish__year=year, publish__month=month, 
        publish__day=day)       
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST': #user sent a comment
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid(): 
            new_comment = comment_form.save(commit=False) #comment is created but still not saved in db
            new_comment.post = post #tie up the comment to the current post
            new_comment.save() #saving the comment in db
    else:
        comment_form = CommentForm()
    
    post_tags_id = post.tags.values_list('id', flat=True) #gets all the id tags of the current post, flat=True makes it flat [1,2,3...]
    similar_posts = Post.published.filter(tags__in=post_tags_id)\
        .exclude(id=post.id)
    # gets all the posts having THAT tag, excluding the current
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags','-publish')[:4]
    # with the help of COunt gets all the posts that have same tags to gather them into SAME_TAGS
    # then orders them with less similar tags in the bottom, and most similat in the top

    return render(request, 'blog/post/detail.html',
        {'post': post, 'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts})

blog_app/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="sidebar">
            <h2>Принимаются донаты :) </h2>
            <p>На странице имеются {% total_posts %} статей на данный момент. </p>
            <h3> Свежие публикации </h3>
            {% show_latest_posts 3 %}
            <h3> Самые обсуждаемые </h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

blog_app/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}
    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}


{% if new_comment %}
    <h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
<p class="similar_posts">
        Similar Posts:
            {% for post in post.tags.all %}
                <a href='{% url "blog_app:post_list_by_tag" post.slug %}'>
                {{ post.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
{% endblock %}

blog_app/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}"> {{ post.title }} </a></li>
    {% endfor %}
</ul>

blog_app/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>Новости 24/7</h1>
    {% if tag %}
        <h2> Posts tagged with "{{ tag.name }} </h2>"
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            <h4><p class="tags">Tags: {{ post.tags.all|join:", " }}</p> </h6>
        </h2>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|truncatewords:30|linebreaks }}
    <p class="tags">
        Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
{% endfor %}
    {% include "pagination.html" with page=posts %} 
{% endblock %}

blog_app/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
    <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>